#Arnav Singh
#Applied Data Science 
#Assignment 1

1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.


In [1]:
name = "Arnav Singh"
age = 20

print("Name:", name)
print("Age:", age)

Name: Arnav Singh
Age: 20


2. X="Datascience is used to extract meaningful insights." Split the string

In [2]:
X = "Datascience is used to extract meaningful insights."
split_str = X.split()
print("String after splitting", split_str)

String after splitting ['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


3. Make a function that gives multiplication of two numbers

In [3]:
def multiply(a,b):
    return a * b

res = multiply(6,9)
print("Multiplication result:", res)

Multiplication result: 54


4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [9]:
dict={"Madhya Pradesh": "Bhopal", "Uttar Pradesh": "Lucknow","Bihar": "Patna","Chhattisgarh": "Raipur","Goa": "Panaji"}
print("Keys:",dict.keys())
print("Values:",dict.values())

Keys: dict_keys(['Madhya Pradesh', 'Uttar Pradesh', 'Bihar', 'Chhattisgarh', 'Goa'])
Values: dict_values(['Bhopal', 'Lucknow', 'Patna', 'Raipur', 'Panaji'])


5. Create a list of 1000 numbers using range function.

In [12]:
list1=[]
for i in range(1,1001):
  list1.append(i)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

6. Create an identity matrix of dimension 4 by 4

In [13]:
import numpy as np
mat1= np.eye(4)
mat1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. Create a 3x3 matrix with values ranging from 1 to 9

In [18]:
mat2 = np.arange(1, 10).reshape(3, 3)
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Create 2 similar dimensional array and perform sum on them.

In [26]:
mat3 = np.ones(16).reshape(4, 4)
print(mat3)
print()

mat4 = np.arange(1, 17).reshape(4, 4)
print(mat4)
print()

print("Summation of Mat3 and Mat4:")
print(mat3+mat4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Summation of Mat3 and Mat4:
[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]]


9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [27]:
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

num_days = (end_date - start_date).days + 1
date_array = np.array([start_date + timedelta(days=i) for i in range(num_days)])

print(date_array)

[datetime.datetime(2023, 2, 1, 0, 0) datetime.datetime(2023, 2, 2, 0, 0)
 datetime.datetime(2023, 2, 3, 0, 0) datetime.datetime(2023, 2, 4, 0, 0)
 datetime.datetime(2023, 2, 5, 0, 0) datetime.datetime(2023, 2, 6, 0, 0)
 datetime.datetime(2023, 2, 7, 0, 0) datetime.datetime(2023, 2, 8, 0, 0)
 datetime.datetime(2023, 2, 9, 0, 0) datetime.datetime(2023, 2, 10, 0, 0)
 datetime.datetime(2023, 2, 11, 0, 0) datetime.datetime(2023, 2, 12, 0, 0)
 datetime.datetime(2023, 2, 13, 0, 0) datetime.datetime(2023, 2, 14, 0, 0)
 datetime.datetime(2023, 2, 15, 0, 0) datetime.datetime(2023, 2, 16, 0, 0)
 datetime.datetime(2023, 2, 17, 0, 0) datetime.datetime(2023, 2, 18, 0, 0)
 datetime.datetime(2023, 2, 19, 0, 0) datetime.datetime(2023, 2, 20, 0, 0)
 datetime.datetime(2023, 2, 21, 0, 0) datetime.datetime(2023, 2, 22, 0, 0)
 datetime.datetime(2023, 2, 23, 0, 0) datetime.datetime(2023, 2, 24, 0, 0)
 datetime.datetime(2023, 2, 25, 0, 0) datetime.datetime(2023, 2, 26, 0, 0)
 datetime.datetime(2023, 2, 27, 0,

10. Given a dictionary, convert it into corresponding dataframe and display it

    dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [28]:
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}

df = pd.DataFrame.from_dict(dictionary)
print(df)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
